version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 0"
  - dependency-name: setuptools
    versions:
    - ">= 0"
  - dependency-name: twine
    versions:
    - ">= 0"
  - dependency-name: wheel
    versions:
    - ">= 0"
  - dependency-name: pollination-dragonfly-annual-energy-use
    versions:
    - 0.2.12
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
